// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAREfCm2_KcmKG5b1EoMyUnXkTGP-XuZpc',
    appId: '1:655558333883:web:69f607b4883ae7f273609e',
    messagingSenderId: '655558333883',
    projectId: 'attnote-dd1f2',
    authDomain: 'attnote-dd1f2.firebaseapp.com',
    storageBucket: 'attnote-dd1f2.firebasestorage.app',
    measurementId: 'G-BVCHVEKNKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZcM4bhMuXrtEhCOjQUKn-6rUjkm2FBw',
    appId: '1:655558333883:android:2b136f9b0a1bbb0373609e',
    messagingSenderId: '655558333883',
    projectId: 'attnote-dd1f2',
    storageBucket: 'attnote-dd1f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8fKw7-2SZQ5N1KpPmZJUWR1ZCUJhsELw',
    appId: '1:655558333883:ios:0df2fe044f10933273609e',
    messagingSenderId: '655558333883',
    projectId: 'attnote-dd1f2',
    storageBucket: 'attnote-dd1f2.firebasestorage.app',
    iosBundleId: 'com.example.attnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8fKw7-2SZQ5N1KpPmZJUWR1ZCUJhsELw',
    appId: '1:655558333883:ios:0df2fe044f10933273609e',
    messagingSenderId: '655558333883',
    projectId: 'attnote-dd1f2',
    storageBucket: 'attnote-dd1f2.firebasestorage.app',
    iosBundleId: 'com.example.attnote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAREfCm2_KcmKG5b1EoMyUnXkTGP-XuZpc',
    appId: '1:655558333883:web:ccab3f73becd138e73609e',
    messagingSenderId: '655558333883',
    projectId: 'attnote-dd1f2',
    authDomain: 'attnote-dd1f2.firebaseapp.com',
    storageBucket: 'attnote-dd1f2.firebasestorage.app',
    measurementId: 'G-336VK0VHX4',
  );
}
