// screens/create_class_screen.dart

import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../services/firestore_service.dart';
import '../models/subject_model.dart';

class CreateClassScreen extends StatefulWidget {
  const CreateClassScreen({super.key});

  @override
  State<CreateClassScreen> createState() => _CreateClassScreenState();
}

class _CreateClassScreenState extends State<CreateClassScreen> {
  final _subjectCtrl = TextEditingController();
  final _departmentCtrl = TextEditingController();
  final _semesterCtrl = TextEditingController();
  final _sectionCtrl = TextEditingController();

  // Split Attendance Controllers
  bool _isSplitAttendance = false;
  final List<Map<String, dynamic>> _attendanceParts = [];

  // Timetable
  final Map<String, int> _timetable = {};

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirestoreService _firestoreService =
      FirestoreService(); // Added service

  bool _loading = false;

  void _addAttendancePart() {
    setState(() {
      _attendanceParts.add({
        'name': TextEditingController(),
        'startDate': DateTime.now(),
        'endDate': DateTime.now().add(const Duration(days: 30)),
      });
    });
  }

  void _removeAttendancePart(int index) {
    setState(() {
      _attendanceParts.removeAt(index);
    });
  }

  Future<void> _selectDate(
    BuildContext context,
    int index,
    bool isStart,
  ) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: isStart
          ? _attendanceParts[index]['startDate']
          : _attendanceParts[index]['endDate'],
      firstDate: DateTime(2020),
      lastDate: DateTime(2030),
    );
    if (picked != null) {
      setState(() {
        if (isStart) {
          _attendanceParts[index]['startDate'] = picked;
        } else {
          _attendanceParts[index]['endDate'] = picked;
        }
      });
    }
  }

  Future<void> _saveClass() async {
    final subjectNameRaw = _subjectCtrl.text;
    final departmentRaw = _departmentCtrl.text;
    final semesterRaw = _semesterCtrl.text;
    final sectionRaw = _sectionCtrl.text;

    if (subjectNameRaw.isEmpty ||
        departmentRaw.isEmpty ||
        semesterRaw.isEmpty ||
        sectionRaw.isEmpty) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('All fields are required')));
      return;
    }

    // Validate parts if split attendance is enabled
    List<AttendancePart> parts = [];
    if (_isSplitAttendance) {
      if (_attendanceParts.isEmpty) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Please add at least one attendance part'),
          ),
        );
        return;
      }
      for (var part in _attendanceParts) {
        final name = (part['name'] as TextEditingController).text;
        if (name.isEmpty) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('All part names are required')),
          );
          return;
        }
        parts.add(
          AttendancePart(
            name: name,
            startDate: part['startDate'],
            endDate: part['endDate'],
          ),
        );
      }
    }

    final subjectName = subjectNameRaw;
    final department = departmentRaw;
    final className = semesterRaw + sectionRaw;

    setState(() => _loading = true);
    try {
      final uid = FirebaseAuth.instance.currentUser!.uid;

      // 1. Create Global Subject
      final globalSubject = Subject(
        id: '', // Generated by firestore or ignored in createGlobalSubject
        name: subjectName,
        isGlobal: true,
        createdBy: uid,
        department: department,
        section: className,
        attendanceParts: parts,
        timetable: _timetable,
      );

      final globalId = await _firestoreService.createGlobalSubject(
        globalSubject,
      );

      // 2. Create Local Staff Class Record (for staff dashboard)
      await _firestore.collection('users').doc(uid).collection('classes').add({
        'subjectName': subjectName,
        'department': department,
        'className': className,
        'attendanceParts': parts
            .map((x) => x.toMap())
            .toList(), // Optional: Store locally too
        'isGlobal': true,
        'globalSubjectId': globalId,
      });

      if (!mounted) return;

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Class and Global Subject created successfully'),
        ),
      );
      Navigator.pop(context);
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Error creating class: $e')));
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  void dispose() {
    _subjectCtrl.dispose();
    _departmentCtrl.dispose();
    _semesterCtrl.dispose();
    _sectionCtrl.dispose();
    for (var part in _attendanceParts) {
      (part['name'] as TextEditingController).dispose();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Scaffold(
      appBar: AppBar(title: const Text('Create New Class')),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Class Details Section
                  Text(
                    'Class Details',
                    style: theme.textTheme.titleSmall?.copyWith(
                      fontWeight: FontWeight.w600,
                      color: colorScheme.primary,
                    ),
                  ),
                  const SizedBox(height: 12),

                  TextField(
                    controller: _subjectCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Subject Name',
                      prefixIcon: Icon(Icons.subject_outlined),
                      hintText: 'e.g. Mathematics',
                      border: OutlineInputBorder(),
                    ),
                  ),
                  const SizedBox(height: 14),
                  TextField(
                    controller: _departmentCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Department',
                      prefixIcon: Icon(Icons.business_outlined),
                      hintText: 'e.g. IT',
                      border: OutlineInputBorder(),
                    ),
                  ),
                  const SizedBox(height: 14),
                  Row(
                    children: [
                      Expanded(
                        child: TextField(
                          controller: _semesterCtrl,
                          decoration: const InputDecoration(
                            labelText: 'Semester',
                            hintText: 'e.g. V',
                            prefixIcon: Icon(Icons.school_outlined),
                            border: OutlineInputBorder(),
                          ),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: TextField(
                          controller: _sectionCtrl,
                          decoration: const InputDecoration(
                            labelText: 'Section',
                            hintText: 'e.g. B',
                            prefixIcon: Icon(Icons.group_outlined),
                            border: OutlineInputBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),

                  const SizedBox(height: 24),

                  // Split Attendance Section
                  Text(
                    'Attendance Structure',
                    style: theme.textTheme.titleSmall?.copyWith(
                      fontWeight: FontWeight.w600,
                      color: colorScheme.primary,
                    ),
                  ),
                  const SizedBox(height: 8),

                  Card(
                    elevation: 0,
                    color: colorScheme.surfaceContainerLow,
                    child: SwitchListTile(
                      title: const Text('Split Attendance'),
                      subtitle: Text(
                        'Divide into parts (e.g. Term 1, Term 2)',
                        style: theme.textTheme.bodySmall?.copyWith(
                          color: colorScheme.onSurfaceVariant,
                        ),
                      ),
                      value: _isSplitAttendance,
                      onChanged: (val) {
                        setState(() {
                          _isSplitAttendance = val;
                          if (val && _attendanceParts.isEmpty) {
                            _addAttendancePart();
                          }
                        });
                      },
                    ),
                  ),

                  // Attendance Parts List
                  if (_isSplitAttendance) ...[
                    const SizedBox(height: 10),
                    Text(
                      'Attendance Parts:',
                      style: theme.textTheme.titleSmall,
                    ),
                    const SizedBox(height: 8),
                    ListView.builder(
                      shrinkWrap: true,
                      physics: const NeverScrollableScrollPhysics(),
                      itemCount: _attendanceParts.length,
                      itemBuilder: (context, index) {
                        return Card(
                          margin: const EdgeInsets.only(bottom: 8),
                          child: Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: Column(
                              children: [
                                Row(
                                  children: [
                                    Expanded(
                                      child: TextField(
                                        controller:
                                            _attendanceParts[index]['name'],
                                        decoration: InputDecoration(
                                          labelText:
                                              'Part Name (e.g. Term ${index + 1})',
                                        ),
                                      ),
                                    ),
                                    IconButton(
                                      icon: Icon(
                                        Icons.delete,
                                        color: colorScheme.error,
                                      ),
                                      onPressed: () =>
                                          _removeAttendancePart(index),
                                    ),
                                  ],
                                ),
                                Row(
                                  children: [
                                    TextButton(
                                      onPressed: () =>
                                          _selectDate(context, index, true),
                                      child: Text(
                                        'Start: ${_attendanceParts[index]['startDate'].toString().split(' ')[0]}',
                                      ),
                                    ),
                                    const Text('-'),
                                    TextButton(
                                      onPressed: () =>
                                          _selectDate(context, index, false),
                                      child: Text(
                                        'End: ${_attendanceParts[index]['endDate'].toString().split(' ')[0]}',
                                      ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                          ),
                        );
                      },
                    ),
                    FilledButton.icon(
                      onPressed: _addAttendancePart,
                      icon: const Icon(Icons.add),
                      label: const Text('Add Part'),
                    ),
                  ],

                  const SizedBox(height: 24),

                  // Timetable Section
                  Text(
                    'Timetable (Optional)',
                    style: theme.textTheme.titleSmall?.copyWith(
                      fontWeight: FontWeight.w600,
                      color: colorScheme.primary,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'Set class schedule for automatic attendance',
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: colorScheme.onSurfaceVariant,
                    ),
                  ),
                  const SizedBox(height: 12),

                  ...[
                    'Monday',
                    'Tuesday',
                    'Wednesday',
                    'Thursday',
                    'Friday',
                    'Saturday',
                    'Sunday',
                  ].map((day) {
                    return Card(
                      elevation: 0,
                      color: colorScheme.surfaceContainerLow,
                      margin: const EdgeInsets.only(bottom: 6),
                      child: Padding(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 16,
                          vertical: 8,
                        ),
                        child: Row(
                          children: [
                            Expanded(
                              flex: 2,
                              child: Text(
                                day,
                                style: theme.textTheme.bodyMedium?.copyWith(
                                  fontWeight: FontWeight.w500,
                                ),
                              ),
                            ),
                            Expanded(
                              child: DropdownButton<int>(
                                value: _timetable[day] ?? 0,
                                isExpanded: true,
                                items: List.generate(6, (index) {
                                  return DropdownMenuItem(
                                    value: index,
                                    child: Text(
                                      index == 0
                                          ? 'None'
                                          : '$index class${index > 1 ? 'es' : ''}',
                                      style: theme.textTheme.bodyMedium,
                                    ),
                                  );
                                }),
                                onChanged: (value) {
                                  setState(() {
                                    if (value == null || value == 0) {
                                      _timetable.remove(day);
                                    } else {
                                      _timetable[day] = value;
                                    }
                                  });
                                },
                              ),
                            ),
                          ],
                        ),
                      ),
                    );
                  }),

                  const SizedBox(height: 24),
                  SizedBox(
                    width: double.infinity,
                    child: FilledButton.icon(
                      onPressed: _saveClass,
                      icon: const Icon(Icons.add_rounded),
                      label: const Text('Create Class'),
                    ),
                  ),
                  const SizedBox(height: 16),
                ],
              ),
            ),
    );
  }
}
